networks:
  expense: {}
volumes:
  mysql:

services:
  mysql:
    image: mysql:1.0.0
    container_name: mysql
    networks:
      - expense
    volumes:
      - mysql:/var/lib/mysql

  backend:
    image: backend:1.0.0
    command: sh -c "sleep 10 && node /opt/backend/index.js"
    container_name: backend
    networks:
      - expense
    depends_on:
      - mysql
    expose:
      - "8080"   # 👈 backend listens on 8080

  frontend:
    image: frontend:1.0.0
    container_name: frontend
    networks:
      - expense
    ports:
      - "80:80"
    depends_on:
      - backend
